### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by jiangfan2** [mipuc/hts-engine-world#1]
when I make after ./configure,it get err as follow:

make[1]: Entering directory `/home/ll/dev/hts-engine-world/bin'
gcc -DPACKAGE_NAME=\"hts_engine_API\" -DPACKAGE_TARNAME=\"hts_engine_API\" -DPACKAGE_VERSION=\"1.10\" -DPACKAGE_STRING=\"hts_engine_API\ 1.10\" -DPACKAGE_BUGREPORT=\"hts-engine-users@lists.sourceforge.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"hts_engine_API\" -DVERSION=\"1.10\" -DHAVE_LIBM=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_VPRINTF=1 -DHAVE_SQRT=1 -DHAVE_STRCHR=1 -DHAVE_STRRCHR=1 -DHAVE_STRSTR=1 -I.  -I ../include   -g -O2 -MT hts_engine.o -MD -MP -MF .deps/hts_engine.Tpo -c -o hts_engine.o hts_engine.c
mv -f .deps/hts_engine.Tpo .deps/hts_engine.Po
gcc  -g -O2   -o hts_engine hts_engine.o ../lib/libHTSEngine.a -lm 
../lib/libHTSEngine.a(HTS_gstream.o): In function `HTS_GStreamSet_clear':
/home/ll/dev/hts-engine-world/lib/HTS_gstream.c:208: undefined reference to `DestroyMemory'
../lib/libHTSEngine.a(HTS_gstream.o): In function `HTS_GStreamSet_create':
/home/ll/dev/hts-engine-world/lib/HTS_gstream.c:144: undefined reference to `synthesizeWorld'
collect2: error: ld returned 1 exit status
make[1]: *** [hts_engine] Error 1
make[1]: Leaving directory `/home/ll/dev/hts-engine-world/bin'
make: *** [all-recursive] Error 1

**Comment by mipuc** [comment]
Please try the new committed version
